platform :ios, '12.0'
use_frameworks!

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'mParticle-Apple-SDK', '~> 8'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end
