platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'mParticle-Apple-SDK', '~> 8.5'
  pod 'mParticle-Appboy', '~> 8.0'
  pod 'mParticle-Radar', '~> 8.0'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end

# def fix_config(config)
#   # https://github.com/CocoaPods/CocoaPods/issues/8891
#   if config.build_settings['DEVELOPMENT_TEAM'].nil?
#     config.build_settings['DEVELOPMENT_TEAM'] = '47UH3S589T'
#   end
# end

# post_install do |installer|
#   installer.generated_projects.each do |project|
#     project.build_configurations.each do |config|
#         fix_config(config)
#     end
#     project.targets.each do |target|
#       target.build_configurations.each do |config|
#         fix_config(config)
#       end
#     end
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
          end
      end
  end
end
